import Foundation
import CoreData

// ShoppingItemEntity is generated by Core Data from the .xcdatamodeld file
// This file contains helper extensions

extension ShoppingItemEntity {
    var displayQuantity: String {
        if let unit = unit, !unit.isEmpty {
            return "\(quantity) \(unit)"
        } else if quantity > 1 {
            return "\(quantity) шт"
        }
        return ""
    }

    var sourceDisplayName: String {
        switch addedBy {
        case "ios":
            return "Приложение"
        case "telegram":
            return "Telegram"
        case "alice":
            return "Алиса"
        default:
            return addedBy ?? "Неизвестно"
        }
    }

    var categoryDisplay: String {
        if let icon = categoryIcon, let name = categoryName {
            return "\(icon) \(name)"
        }
        return categoryName ?? "Другое"
    }
}
