import Foundation
import CoreData

// ShoppingListEntity is generated by Core Data from the .xcdatamodeld file
// This file contains helper extensions

extension ShoppingListEntity {
    var itemsArray: [ShoppingItemEntity] {
        let set = items as? Set<ShoppingItemEntity> ?? []
        return Array(set).sorted { ($0.createdAt ?? Date()) < ($1.createdAt ?? Date()) }
    }

    var uncheckedItemsCount: Int {
        let set = items as? Set<ShoppingItemEntity> ?? []
        return set.filter { !$0.isChecked }.count
    }

    var checkedItemsCount: Int {
        let set = items as? Set<ShoppingItemEntity> ?? []
        return set.filter { $0.isChecked }.count
    }

    var completionPercentage: Double {
        let total = (items as? Set<ShoppingItemEntity>)?.count ?? 0
        guard total > 0 else { return 0 }
        return Double(checkedItemsCount) / Double(total)
    }
}
